version: '3'
services:
  go:
    container_name: todo_golang
    build:
      context: .
      dockerfile: ./docker/api/Dockerfile
    command: air -c .air.toml
    stdin_open: true
    tty: true
    volumes:
      - ./src:/app
    environment:
      TZ: Asia/Tokyo
    ports:
      - "80:8080"
      - "2345:2345"
    depends_on:
      - "db"

  db:
    image: mysql:5.7
    container_name: todo_mysql_host # phpMyAdminサービスのPMA_HOSTSに設定する
    environment:
      MYSQL_ROOT_PASSWORD: ${ROOTPASS}
      MYSQL_DATABASE: ${DATABASE}
      MYSQL_USER: ${USERNAME}
      MYSQL_PASSWORD: ${USERPASS}
      TZ: 'Asia/Tokyo'
      LC_ALL: 'ja_JP.UTF-8'
      LANG: "ja_JP.UTF-8"
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    volumes:
      - ./docker/db/data:/var/lib/mysql
      - ./docker/db/my.cnf:/etc/mysql/conf.d/my.cnf
    ports:
      - "3306:3306"

volumes:
  db-data:
    driver: local
